version: '3'

services:
  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Toor@1234
      POSTGRES_DB: general
    volumes:
      - postgres-volume:/data/postgres


volumes:
  postgres-volume:
